### PR TITLE
[#393] Update the Bootstrap vendor file

### LINKED ISSUE #393: Import bootstrap SCSS functions before variables in order to benefit from scss functions
## Why

Currently, we set variables like `2rem; // 32px`. Because the variables are imported before the `@import 'bootstrap/scss/functions';`. According to bootstrap documentation, we can import the variable overrides after it and use these functions :)

- https://getbootstrap.com/docs/5.2/migration/
- SASS doc from bootstrap https://getbootstrap.com/docs/5.3/customize/sass/#importing
- Suggestion by Olivier: https://github.com/nimblehq/rails-templates/pull/390#discussion_r1107929525
 
## Who Benefits?

Developers when codding the scss variables.

### PR DESCRIPTION
**Pull request by andyduong1920**
close #393

## What happened 👀

Update the Bootstrap vendor file on Bootstrap 5.3

## Insight 📝

This is follow the [guide on the Bootstrap 5.3](https://getbootstrap.com/docs/5.3/customize/sass/#importing) with some modifier, we already used this in our projects without any error.

## Proof Of Work 📹

On the file changes tab

### CODE REVIEW

**Comment by malparty** [comment]
@andyduong1920 did you try it on a project with custom variables? 👀 
If not, I will plan some time next week to test that format in a real project 💭

**Comment by andyduong1920** [comment]
> @andyduong1920 did you try it on a project with custom variables? 👀 If not, I will plan some time next week to test that format in a real project 💭

@malparty I'm not sure about the custom variable topic hehe

**Comment by malparty** [comment]
Ok, let me plan a small test (tomorrow after lunch 🙇 ) just to ensure it's all good in "complex" situations ^^

**Review by tyrro — APPROVED** [review]

**Review by olivierobert — APPROVED** [review]

**Review by malparty — APPROVED** [review]
Tested with Fl app, I just got an issue with the variable used by Choice, but this is not a blocker at all. So everything else looks good!

**Pull request merged**
